# Generated by Django 4.2.3 on 2023-11-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0004_alter_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
