# Generated by Django 4.2.3 on 2023-11-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0007_alter_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='title',
            field=models.CharField(default='', max_length=400),
        ),
    ]
