# Generated by Django 4.2.3 on 2023-11-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0008_user_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_job',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('filled', 'Filled')], default='available', max_length=20),
        ),
    ]
