# Generated by Django 4.2.3 on 2023-11-21 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0010_remove_application_work_application_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_job',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
