# Generated by Django 4.2.3 on 2023-11-23 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0015_alter_offer_job_created_by_alter_offer_job_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
