# Generated by Django 4.2.3 on 2023-11-28 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0017_remove_offer_job_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joboffers.user_profile'),
        ),
    ]
