# Generated by Django 4.2.3 on 2023-11-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0018_application_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_sms', to='joboffers.application'),
        ),
    ]
