# Generated by Django 4.2.3 on 2023-11-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0021_rename_date_sms_timestamp_remove_sms_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
